name: Build
on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        type: choice
        options:
          - 16.5
          - 17.5
          - 18.6
        required: true
        default: 18.6

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Downlaod SideStore
        run: wget "https://github.com/SideStore/SideStore/releases/download/0.6.2/SideStore.ipa"

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ss-ipa${{ github.run_number }}
          name: SideStore iPhone (${{ github.run_number }}) 
          files: SideStore.ipa
          draft: true
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
