name: Get Ventoy
on:
 workflow_dispatch:
 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Get Ventoy
    runs-on: macos-latest
    permissions:
      contents: write

    steps:        
      - name: Download Ventoy
        run: wget "https://sf-west-interserver-1.dl.sourceforge.net/project/ventoy/v1.1.10/ventoy-1.1.10-windows.zip?viasf=1"

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ventoy-${{ github.run_number }}
          name: Ventoy v1.1.10 (${{ github.run_number }}) 
          files: ventoy-1.1.10-windows.zip
          draft: true

    
