name: Build IPA with FLEX and YouMod test
on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        type: choice
        options:
          - 16.5
          - 17.5
          - 18.6
        required: true
        default: 18.6

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    name: Build IPA with FLEX and YouMod test
    runs-on: macos-latest
    permissions:
      contents: write
    # Force Node.js 24 (Temporary fix for the Github Releases Node.js 20 warnings)
    # https://archive.org/download/com.google.ios.youtube-20.21.6-Decrypted/com.google.ios.youtube-20.21.6-Decrypted.ipa
    # git clone --quiet https://github.com/PoomSmart/IAmYouTube.git
    # git clone --quiet https://github.com/PoomSmart/YouTube-X.git
    # git clone --quiet https://github.com/PoomSmart/YTVideoOverlay.git
    # git clone --quiet https://github.com/Tonwalter888/YouMute.git
    # git checkout 1585a3691b2ef0b59d42c40c31639fd8b79e2cd4
    # wget "https://archive.org/download/com.google.ios.youtube-21.21.03-Decrypted/com.google.ios.youtube-21.21.03-Decrypted.ipa" --no-verbose --quiet -O youtube.ipa
    # wget "https://decrypt.download/api/downloads/fe5e4b75-2754-4265-936f-f150a7bdbcc3" --no-verbose --quiet -O youtube.ipa
    # wget "https://files.catbox.moe/d7q8rb.ipa" --no-verbose --quiet -O youtube.ipa
    # https://files.catbox.moe/lyn4gg.ipa 21.19

    steps:
      - name: Clone
        run: |
          git clone --quiet --depth=1 --recurse https://github.com/PoomSmart/FLEXing.git
          git clone --quiet --depth=1 https://github.com/Tonwalter888/FLEXHelperForYT.git
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTIcons.git
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git
          git clone --quiet https://github.com/grohit1810/YouMod.git
          wget "https://archive.org/download/com.google.ios.youtube_21.22.04_und3fined/com.google.ios.youtube_21.22.04_und3fined.ipa" --no-verbose --quiet -O youtube.ipa

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH environments variable
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV 

      - name: Setup Theos
        run: |
            git clone --quiet --recurse-submodules https://github.com/theos/theos.git
            git clone --quiet --depth=1 -n --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
            cd iOS-SDKs
            git sparse-checkout set --no-cone iPhoneOS18.6.sdk
            git checkout --quiet
            mv *.sdk "$THEOS/sdks"
            cd
            cd theos
            git checkout 9bc73406cf80b711ef4d02c15ff1dedc4478a275
            
      - name: Clone headers
        run: |
          if [ ! -d "$THEOS/include/YouTubeHeader" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git "$THEOS/include/YouTubeHeader"
          else
            cd $THEOS/include/YouTubeHeader
            git pull --quiet --force
            cd ${{ github.workspace }}
          fi
          
          if [ ! -d "$THEOS/include/PSHeader" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git "$THEOS/include/PSHeader"
          else
            cd $THEOS/include/PSHeader
            git pull --quiet --force
            cd ${{ github.workspace }}
          fi

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Build things
        run: |
          cd YouMod
          git switch feature/add-sponsorblock
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youmod.deb
          cd ..
          cd FLEXing
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless ARCHS=arm64
          mv packages/*.deb ${{ github.workspace }}/flex.deb
          cd ..
          cd YTIcons
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/yticons.deb
          cd ..
          cd FLEXHelperForYT
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/flexhelper.deb
          cd ..
          cd YTABConfig
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ab.deb

      - name: Inject Tweaks Into IPA
        run: |
          tweaks=""
          
          for f in *.deb; do
            tweaks="$tweaks $f"
          done
          
          cyan -i youtube.ipa -o WaterTest_FLEX.ipa -uwef $tweaks -n "WaterTest_FLEX" -b com.waterdev.youtube.flex
          
      - name: Create a Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: watertest-ipa${{ github.run_number }}
          name: WaterTest_FLEX (${{ github.run_number }}) 
          files: WaterTest_FLEX.ipa
          draft: true
