name: Build Alderis
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Alderis
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Install tbd
        run: |
           wget --quiet --no-verbose "https://archive.org/download/luma-fusion-5.4.3-26.0-le-ti/Minecraft_1.26.32_13.0_LeTi.ipa" -O minecraft.ipa

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: deb${{ github.run_number }}
          name: MC (${{ github.run_number }}) 
          files: minecraft.ipa
          draft: true
